# Generated by Django 2.2.8 on 2019-12-14 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='published_date',
        ),
        migrations.AddField(
            model_name='condition',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
