# Generated by Django 2.2.8 on 2019-12-14 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='finish_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
