# Generated by Django 2.2.8 on 2019-12-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0002_schedule_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='place',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='schedule',
            name='roop_flag',
            field=models.BooleanField(default=False),
        ),
    ]
