# Generated by Django 2.2.8 on 2019-12-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0004_categories_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_time',
            new_name='finish_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
    ]
